# Starship command prompt configuration file. Colour choice and over-use of emoji
# is to help blend in with Ubuntu MATE default theme, Ambiant-Mate.

# disable starship from forcing a new line to be taken. Solved the empty line 
# at start of terminal
add_newline = false

[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➟"
[character]      # The name of the module we are configuring is "character"
#use_symbol_for_status = true
#symbol = "  ➟"     # The "symbol" segment is being set to "➜"
error_symbol = "  ✗"
#style_success = "bold #00A652"
#style_failure = "bold #df382c"

# Hide the username. The username will only show in certain scenarios
[username]
disabled = true

# shows the hostname on new lines
[hostname]
ssh_only = true
#suffix = ">>"
trim_at = ".companyname.com"
format =  "[$hostname](bold red)@"
disabled = true
style = "bold italic #87A752"

[nix_shell]
disabled = false
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = 'via [☃️ $state( \($name\))](bold blue) '

# configure directory
[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic #87A752"

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow)"
show_milliseconds = false
disabled = false
style = "bold italic #87A752"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[jobs]
symbol = "+ "
threshold = 1


[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# when capacity is over 30%, the battery indicator will not be displayed


